#!/bin/bash

REMOTE_HOST=linode.mattcaron.net
DESTINATION=$HOME/attic/backup/linode
BACKUP_KEY=$HOME/.ssh/id_rsa_backup

rsync --rsh="ssh -o ControlMaster=no -i $BACKUP_KEY -l root" \
-Havzh --delete --relative --out-format="" \
$REMOTE_HOST:/etc \
$REMOTE_HOST:/home \
$REMOTE_HOST:/var/lib/matrix-synapse \
$REMOTE_HOST:/var/lib/mysql \
$REMOTE_HOST:/var/lib/postgresql \
$REMOTE_HOST:/var/lib/sympa \
$REMOTE_HOST:/var/spamassassin \
$DESTINATION | \
grep "[[:alnum:]]" | grep -v ^deleting
    if [ ${PIPESTATUS[0]} -ne 0 ]; then 
        echo -n "rsync exited with an error. " 
        echo "Check above for specific failures." 
    else 
        echo -n "rsync reported no errors. "
        echo "Check above, in case it's lying."
    fi 

