#!/bin/bash

BACKUP_PATH=$HOME/attic/backup/`hostname`

FILE=$(mktemp $BACKUP_PATH/mysql.`date +%F`.XXXXXXXXXX)

if [ "$?" -eq "0" ]; then
    mysqldump --defaults-extra-file=$BACKUP_PATH/mysql.pw \
              --default-character-set=utf8mb4 \
              -u root --all-databases --single-transaction \
              --events > $FILE && lzma $FILE
else
    echo "Error creating temporary file"
fi
