#!/bin/bash

LABEL=external_backup
DISK=/mnt/$LABEL
HOST=`hostname`
TARGET=$DISK/$HOST
SOURCES="/home /etc /var /mnt/shared /mnt/time_machine"

# /mnt/shared is backed up, but we bind mount it everywhere, so don't
# back up the copies too. Also, don't back up any rsnapshot dirs.
EXCLUDES="--exclude /home/*/shared -exclude rsnapshot"

if [ `whoami` = 'root' ]; then

    sudo mount $DISK

    if [ $? != "0" ]; then
        echo "Error mounting $DISK. Aborting."
    else
        mkdir $TARGET
        
        date
        echo `date` > $TARGET/backup_date
        
        echo "Writing package list.."
            # dpkg -l | awk '{print $2}' > $TARGET/package_list
        dpkg --get-selections > $TARGET/package_list
        
        for source in $SOURCES; do
	    echo "Backing up $source...."
            # .gvfs is a special fuse mount and messes up rsync.
            # You can use -x, but if I ever do a funky mount that I want
            # automatically backed up too, I'll drive myself crazy trying
            # to find out why it's not working.
	    rsync -Hah --delete --exclude ".gvfs" $EXCLUDES $source $TARGET
        done
        
        df -h $DISK

        umount $DISK
        
        echo "Done!"
    fi
else
    echo "run this as root"
fi

